### ISSUE TITLE
Currently the compiler requires `id` to be present in the source `.model_info`

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/lexical-models#10]
Currently the compiler does require `id` to be present in the source `.model_info` which is technically a bug; we should instead pull that from the folder name. I will open an issue.

This is a problem because:

1. The [spec](https://help.keyman.com/developer/cloud/model_info/1.0/) says that `id` is not required.
2. It's WETter than it needs to be.

_Originally posted by @mcdurdin in https://github.com/keymanapp/lexical-models/pull/7#issuecomment-476359117_

**Comment by eddieantonio** [comment]
I'm currently writing a PR to pull it from the name of the `*.model_info` file. Is that okay, or should it still be from the folder?

**Comment by mcdurdin** [comment]
> I'm currently writing a PR to pull it from the name of the `*.model_info` file. Is that okay, or should it still be from the folder?

Yes, if that is easier, that should be fine because the name of the `.model_info` is required to be the same as the folder name.
