### ISSUE TITLE
feat(nrc.en.mtnt): Add languageUsesCasing flag

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/lexical-models#108]
This should be a bug on https://github.com/keymanapp/lexical-models/ against the MTNT model:

https://github.com/keymanapp/lexical-models/blob/11b70de8daab9c54466d7fac312014cfcb7bd118/release/nrc/nrc.en.mtnt/source/nrc.en.mtnt.model.ts#L1-L5

Cross-reference with https://github.com/keymanapp/keyman/pull/3824.

> The predictive engine will now detect the casing pattern used by the current context (when `languageUsesCasing == true`)...

_Originally posted by @jahorton in https://github.com/keymanapp/keyman/issues/4115#issuecomment-759153281_

**Comment by jahorton** [comment]
A fix for this will likely depend on the linked issue above, as `languageUsesCasing` is 14.0-only at this time.
