### ISSUE TITLE
[brao] bug: not working as expected when there are at least two characters to the left of the caret

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/lexical-models#126]
**Describe the bug**

![Screenshot_1616397167](https://user-images.githubusercontent.com/28331388/111953081-b5c51480-8b18-11eb-8bf0-6053627194f8.png)

When the left context is "[space] ឆ្រ", the suggested words in the banner are not expected, i.e. not the words beginning with ឆ្រ-.

**To Reproduce**

1. Install this keyboard and lm '[brao_keyboard_and_lm.zip](https://github.com/keymanapp/keyman/files/6088954/brao_keyboard_and_lm.zip)' on 14.0.266-beta
2. In the text editor area, type in "ឆ្រ ឆ្រ"
3. Keep the cursor to the right of the second string

**Expected behavior**

Words beginning with ឆ្រ should be in the suggestion.

---

**Keyman for Android:**
 - Device: Pixel 2 API 29
 - OS: Android 10
 - Keyman version: 14.0.266-beta
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: Brao (SIL)
 - Keyboard version: 1.0
 - Language name: Brao

**Additional context**

Regular spaces are used in between words, but the model still cannot provide meaningful suggestion when there are a consonant + subscript (i.e. ឆ្រ) to the left of the caret.

The model is able to provide meaningful and expected suggestions when there are "a consonant and a diacritic/vowel" to the left of the caret, i.e. កំ, ឆា.

កំ >> កំឡាំង | កំប្រឹន | កំប្លីង

![Screenshot_1616397619](https://user-images.githubusercontent.com/28331388/111953979-fbcea800-8b19-11eb-9716-a3aa50d27bf3.png)

ឆា >> ឆា | ឆាល់ | ឆារ

![Screenshot_1616397835](https://user-images.githubusercontent.com/28331388/111954229-59fb8b00-8b1a-11eb-8388-faaa169e3bc9.png)

**Comment by MakaraSok** [comment]
With the custom wordbreak by @jahorton incorporated in https://github.com/keymanapp/lexical-models/pull/122/commits/4953b7eaad8ad80f4a93c50666cacca732a780e2, the suggestion improves.

i.e. ឆ្រ >> ឆ្រង | ឆ្រួយ | ឆ្រូយ

![Screenshot_1616484653](https://user-images.githubusercontent.com/28331388/112110595-b677ac80-8be5-11eb-9b4a-c61ac6e726dc.png)

**Comment by jahorton** [comment]
As suspected, it's literally a matter of having a good wordbreaker in place.

**Comment by DavidLRowe** [comment]
@MakaraSok Has this been resolved? If so, please close the issue. Thanks!

**Comment by MakaraSok** [comment]
This takes a good wordbreak or segmentation for the language to work and it cannot be fixed in this version.

**Comment by jahorton** [comment]
It can, but that's little reason to leave this issue open.  It's a Keyman limitation, not a model limitation.

**Comment by mcdurdin** [comment]
> It can, but that's little reason to leave this issue open. It's a Keyman limitation, not a model limitation.

Where is our issue tracking this limitation in Keyman? This issue was originally open for Keyman and I moved it to the model because I thought it was possible to create a custom wordbreaker in the model. Are you saying that's not possible?

**Comment by jahorton** [comment]
> > It can, but that's little reason to leave this issue open. It's a Keyman limitation, not a model limitation.
> 
> Where is our issue tracking this limitation in Keyman? This issue was originally open for Keyman and I moved it to the model because I thought it was possible to create a custom wordbreaker in the model. Are you saying that's not possible?

It is, but it's nearly on the same level as actually implementing https://github.com/keymanapp/keyman/issues/5025.  It's either that or translating code for an existing Khmer wordbreaker into compatible JS code, both of which are quite sizable tasks.
