### ISSUE TITLE
"welcome.htm" not shown after installation finishes

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/lexical-models#142]
Is it intentional that the `welcome.htm` is not shown after the installation of the LM is finished?

The welcome page does show up when the installation of a keyboard is finished though.

**Comment by DavidLRowe** [comment]
I think that, according to the current design, loading a lexical model does not display welcome.htm.

@mcdurdin Can you confirm?

**Comment by mcdurdin** [comment]
Yes, this is intentional; lexical models are installed automatically when found in the Keyman Cloud catalog, so it would be confusing for the welcome.htm to appear then. welcome.htm is available through the Settings menu.

**Comment by MakaraSok** [comment]
> Yes, this is intentional; lexical models are installed automatically when found in the Keyman Cloud catalog, so it would be confusing for the welcome.htm to appear then. 

How about when the model is installed from file? What is the welcome page for if it is not gonna be shown after being installed? Do we have this piece of info written somewhere?

> welcome.htm is available through the Settings menu.

Unfortunately not, clicking on the "Help link" (as shown in the screenshot) doesn't open anything. Is there any other way to get to the welcome page from Settings?

![Screenshot_1625541099](https://user-images.githubusercontent.com/28331388/124536851-f6843780-de42-11eb-9198-465baf1ee9d0.png)

**Comment by darcywong00** [comment]
> Unfortunately not, clicking on the "Help link" (as shown in the screenshot) doesn't open anything

Ah, that's an oversight. I'll make a Keyman for Android issue for that
