### ISSUE TITLE
chore: Updates for Keyman 15.0

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/lexical-models#165]
I was taking a prelimiary look that this repo will compile with Keyman 15 by setting the following changes in package.json

```
  "dependencies": {
    "@keymanapp/lexical-model-compiler": "^15.0.247-beta",
    "@keymanapp/models-types": "^15.0.247-beta",
  },
  "devDependencies": {
    "jszip": "^3.7.0",
  }
```

I had to add jszip in devDependencies (because of keymanapp/keyman#5770 ?)

---------------------

The build.sh script halts on fv.bea.tsaadane.model.js
```
The target folder contains unexpected files:
fv.bea.tsaadane.model_info source source/fv.bea.tsaadane.model.js source/fv.bea.tsaadane.model.kmp
Aborting build
Aborting with error 999
```

--------------------
Several of the lexical-models had warnings about duplicate words being found, but the build went to completion.
The duplicated words may not be properly encoded though?

For example:
```
Building model /c/src/lexical-models/release/shavian_info/shavian_info.en-shaw.readlex/
wordlist.tsv (10): Warning: 2802 duplicate word ΓÇ£≡ÉææΓÇ¥ found in same file; summing counts
wordlist.tsv (35): Warning: 2802 duplicate word ΓÇ£≡Éæ₧≡Éæ¿≡ÉææΓÇ¥ found in same file; summing counts
```

**Comment by mcdurdin** [comment]
> I had to add jszip in devDependencies (because of [keymanapp/keyman#5770](https://github.com/keymanapp/keyman/pull/5770) ?)

I think we moved from node-zip to jsZip in 15.0.

> The build.sh script halts on fv.bea.tsaadane.model.js

I have addressed this in #169 -- the logic around the validation was not quite right, and stopped rebuilds where the folder wasn't first cleaned.

> The duplicated words may not be properly encoded though?

I think that may just be a console encoding issue rather than a file encoding. The file looks correct when I view it and in my console:

```
Building model /c/Projects/keyman/lexical-models/release/shavian_info/shavian_info.en-shaw.readlex/
wordlist.tsv (10): Warning: 2802 duplicate word “𐑑” found in same file; summing counts
wordlist.tsv (35): Warning: 2802 duplicate word “𐑞𐑨𐑑” found in same file; summing counts

```
