### ISSUE TITLE
[nrc.en.mtnt] Revise wordlist

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/lexical-models#178]
From a team review of the Keyman for Android UX (keymanapp/keyman#7161)

Aside from the contractions issue noted in #143, @mcdurdin notes the default English lexical-model wordlist needs the following adjustments:

## Add common words such as:
* Covid (the original wordlist gathered from reddit was pre-covid)
* Qantas (airline) (and a number of other brands!)
* Coronavirus

## Remove these entries (along with any other typos found):
* becasue	10
* être	6
* reccomend	5
* sheild	5

Is there any value in keeping single-character entries (e.g. `$	1898`)?

**Comment by mcdurdin** [comment]
Yes, remove all single-character entries. Ideally the compiler should do this though...

**Comment by darcywong00** [comment]
Some other suggestions that maybe should be lower-cased (relates to keymanapp/keyman#8164)
Some search results (there's tons more)

Hello
Yep
Ah
Apple (there's apples, but no lower-case apple. Granted this could be the company)
Ashes
Ape
Ark
Alternatively

**Comment by DavidLRowe** [comment]
Is closing this issue waiting on #8164 mentioned above?

**Comment by darcywong00** [comment]
> Is closing this issue waiting on #8164 mentioned above?

Let's keep this issue open. #187 didn't address some of the typos or add new common words.

**Comment by DavidLRowe** [comment]
#221 addresses some of the items raised on this issue. It's still a WIP, but review of the word list is welcome (particularly if there are words I've removed which should be reinstated).

**Comment by sgschantz** [comment]
@DavidLRowe, is this one fixed with #221?

![image](https://github.com/keymanapp/lexical-models/assets/89134789/5625f56f-709b-4e05-bec3-2d6506cb2995)

**Comment by DavidLRowe** [comment]
That is indeed one of the items removed in #221

**Comment by DavidLRowe** [comment]
Some issues fixed by #221 , remainder moved to issue #242
