### ISSUE TITLE
Rebuild certain LMs to use ES3 code generation

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/lexical-models#182]
Relates to keymanapp/keyman#7926

The lexical-model compiler update in the fix keymanapp/keyman#7297 forces ES3 code generation to support Android 5.0 devices.

> this will require version bumps on all affected LMs in order to deploy an updated version with the new version of the compiler once it lands.)

The fix is available in kmlmc 16.0.128-beta

And the following lexical-models will need to be rebuilt:
* dotland.ru.russian
* iles.chp.indigenous_nt
* iles.dgr.indigenous_nt
* sil.bcc-arab.upp_ptwl1
* sil.glk-arab.ptwl1
* sil.kjg-laoo.ptwl1
* wyc_eth.mym-latn.me_en

**Comment by DavidLRowe** [comment]
@darcywong00 IIUC this requires changes to increment the version number (and probably the copyright date) for each of these keyboards, in order to make the newer version available to users. But the only ones who will see any difference are Android 5 users. How urgent is this?

**Comment by darcywong00** [comment]
I think it still depends on 16.0 stable getting released and the kmlmc getting updated before we bump versions.

imho, it's not urgent...
