### ISSUE TITLE
"If omitted, builds all models" is untrue for -b and -t

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/lexical-models#22]
The usage  statement ends with "If omitted, builds all models" (speaking of the optional target argument).
This is true for a bare ./build.sh or for ./build.sh -c, but fails for any combination (that I've tried) that includes either -t or -b.
For example:
$ ./build.sh -c -b
Usage: ./build.sh [-t(est)|-b(uild)|-c(lean)] [-s] [target]
  -t || -test   Runs tests on models
  -b || -build  Creates compiled models
  -c || -clean  Cleans intermediate and output files
  -s            Quiet build
  target        The specific model(s) to build, e.g. release or release/example/en.template
                If omitted, builds all models

**Comment by mcdurdin** [comment]
Closing as obsoleted by #226
