### ISSUE TITLE
bug(nrc.en.mtnt): `we're` not offered as a suggestion for `were`

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/lexical-models#229]
I think this still needs to remain open for @jahorton to confirm this is resolved:
> With a context of "were", I get 3 suggestions:
"were" (frequency 5309)
"weren't" (frequency 385)
"werent" (frequency 16)
>
>"we're" has a frequency of 927 so I would expect it to appear

On my alpha build of Keyman for Android, I'm still not getting "we're" as a suggestion.

_Originally posted by @darcywong00 in https://github.com/keymanapp/lexical-models/issues/143#issuecomment-1656932828_

Reproduced in Keyman 17.0.219-alpha

**Comment by jahorton** [comment]
Inspecting the generated suggestions:  it generally comes in as suggestion #6 - the apostrophe being missing comes at a high cost to the suggestion's probability.  It'll should be available on the upgraded suggestion banner (#7934), at least.

**Comment by mcdurdin** [comment]
I suggest that we elide apostrophe in the searchtermtokey function :grin:

**Comment by jahorton** [comment]
In case it takes a while to come back to...

> -- for this model

Because a _number_ of languages use apostrophes as literal letters, it's best not to erase them as a _default_.  We can definitely tweak the search-term function to make it a model-specific default, though.

**Comment by darcywong00** [comment]
> Inspecting the generated suggestions: it generally comes in as suggestion rank 6 - the apostrophe being missing comes at a high cost to the suggestion's probability. It'll should be available on the upgraded suggestion banner (#7934), at least.

Re-ran on Keyman for Android 17.0.281-beta that includes the upgraded suggestion banner.
"we're" is down to number 7 now...

![were](https://github.com/keymanapp/lexical-models/assets/7358010/1a1519f8-6a7e-4c1b-a48a-2cfbe3bd939c)

**Comment by jahorton** [comment]
See #244 - I've made a model-specific adjustment to the search-term keying function to address this concern.
