### ISSUE TITLE
chore: rebuild all lexical models to address missing low-frequency prefix words

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/lexical-models#246]
**Note**: as this is a compiler bug, all models will likely need recompilation so that they may receive the fix's effects.

_Originally posted by @jahorton in https://github.com/keymanapp/keyman/issues/11074_

After 17.0 is released to stable, and the toolchain is deployed to the lexical-models repository, we need to increment the version number on all lexical models in order to get a fixed version of the models to end users.

**Comment by DavidLRowe** [comment]
@mcdurdin or @darcywong00 what is the status of this issue?

**Comment by darcywong00** [comment]
lexical-models compiler updated updated to 17.0.328 in #227.

I'll raise this during A18S9 sprint planning (checking if there's any other compiler issues to get in before rebuilding all models)

**Comment by jahorton** [comment]
My part's done; the compiler fixes needed are in `kmc-model` stable-17.0 already.

**Comment by darcywong00** [comment]
From A18S9 sprint planing, we'll also wait on #263 before rebuilding all the models
