### ISSUE TITLE
chore: remove model_info source files

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/lexical-models#263]
1. Ensure all data is migrated to .kps.
2. .model_info file is checked in the build script (see also #261)
3. Verify that source .model_info is no longer used by model info compiler
4. Remove all .model_info files from repository

**Comment by darcywong00** [comment]
Will also update kmc to the upcoming 17.0.329

**Comment by mcdurdin** [comment]
> Will also update kmc to the upcoming 17.0.329

That'll be a separate PR
