### ISSUE TITLE
bug(sil.km.cnd): is `សាន់វុ័ណ្ត` valid encoding?

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/lexical-models#288]
សាន់វុ័ណ្ត on line 11570 has the sequence 179C 17BB 17D0 which doesn't look valid to me (and is flagged by Khmer Normalizer).

![image](https://github.com/user-attachments/assets/56e9f506-a75d-4e8c-9dcc-bd4e3457199a)

@MakaraSok can you confirm?

**Comment by mcdurdin** [comment]
@Nnyny can you resolve this? It should be សាន់វ៉័ណ្ត

**Comment by Nnyny** [comment]
I'll look into it, Marc.

**Comment by MakaraSok** [comment]
វ៉័ rendered correctly on Safari, macOS 18.1. Both orders rendered identically this platform.

វុ័ វ ុ ័
វ៉័ វ ៉ ័

<img width="64" alt="image" src="https://github.com/user-attachments/assets/415509c1-2932-4f48-ae0d-34ff46754512">

**Comment by MakaraSok** [comment]
@Nnyny Like ប៉័ង, this word should use the appropriate consonant shifter rather than the below vowel (ុ).

**Comment by mcdurdin** [comment]
Leelawadee UI (incorrect):

![Image](https://github.com/user-attachments/assets/c43091c2-dbd2-4a7c-9528-0d4ae7d6985b)

Busra (correct):

![Image](https://github.com/user-attachments/assets/b647a73d-52bf-416d-8cf1-3fafbe8d231d)
