### ISSUE TITLE
Rename or move example template models

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/lexical-models#45]
I think as we head to beta we should be changing our example template models to use a custom BCP47 tag such as `qaa` so that they don't appear as options to end users, esp as we have an English model now. We definitely need to do this for release. That means a bunch of renaming though!

I would also like to see the English model move out of 'example' and into something real.

An alternative is to move the example models out of release/ into a sample/ folder. Perhaps that's better?

If we do it in alpha, we avoid the need to have backward compat and can just do cleanup on the downloads server. Once we go to beta, we have to deprecate and have a deprecation pathway.

**Comment by eddieantonio** [comment]
Sounds good! So, this is what we have currently (assuming #44 is merged):

```
release
├── example
│   ├── crk.wordlist_wahkohtowin
│   ├── en.custom
│   ├── en.mtnt
│   └── en.wordlist
└── nrc
    └── str.sencoten
```

You want to have this structure instead?

```
sample
└── example
    ├── qaa.cree_wordlist
    ├── qaa.en_custom
    └── qaa.en_wordlist

release
└── nrc
    ├── en.mtnt
    └── str.sencoten
```

**Comment by mcdurdin** [comment]
Yeah, pretty much. But I think if we move the example models into sample/ then we can keep the sensible language tags, because they won't interfere with deployed models. Probably fix the `de` tag back to `en` at the same time ;-)
