### ISSUE TITLE
[newa] Newa autocomplete not working 

### ISSUE THREAD

**Issue by sapradhan** [keymanapp/lexical-models#97]
Not getting proper suggestions after newa wordlist 2.0 is installed. I get only this suggestion (  𑐺𑐕𑐣𑑂𑐟 ) when one letter is typed, (regardless of what is typed) and no suggestions when more than one is typed.
![distributed](https://user-images.githubusercontent.com/5070211/86515232-48ad0a00-be37-11ea-8b9e-34ff6d8c2bfb.png)

However if i build locally and then install, suggestions are shown as expected.
![local-build](https://user-images.githubusercontent.com/5070211/86515235-4ba7fa80-be37-11ea-86a1-b6745564dbbc.png)

[this is the build that works](https://sapradhan.keybase.pub/newa/assets/sapradhan.new-newa.nepal_bhasa.model.kmp?dl=1)

**Comment by darcywong00** [comment]
This seems to involve a change in the lexical-model compiler.
For the model that works, the values are given like `"values":["\ud805"], ...`

The current (broken) compiled model has values like  `"values":["�"],"children":{"�":...`

**Comment by mcdurdin** [comment]
It could be a different node version or a different Developer version?

**Comment by jahorton** [comment]
A note of some possibly-related PRs on the main repo:

- https://github.com/keymanapp/keyman/pull/2477
- https://github.com/keymanapp/keyman/pull/2815

**Comment by darcywong00** [comment]
Some more investigation.
As reported by the user, compiling the lexical model project from Keyman Developer 13.0.109 works (Developer uses nodejs 12.13.1)

While compiling from the lexical-models repo build.sh script (also using kmlmc 13.0.109), the model fails.
My local nodejs version was initially 14.4.0, and I also upgraded to 14.15.0 - both failed.

When I downgraded my local nodejs to [12.19](https://nodejs.org/dist/latest-v12.x/win-x64/) the lexical model compiles fine...

**Comment by jahorton** [comment]
> It could be a different node version ~or a different Developer version?~

Good call, @mcdurdin!

**Comment by darcywong00** [comment]
@sapradhan 
This should be fixed when the Newa model version 2.2 gets released tomorrow.
If you still run into problems, you can re-open this issue.

**Comment by sapradhan** [comment]
it finally works in 2.2
Thanks everybody
